/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    id("org.jetbrains.kotlin.jvm")
}

dependencies {
    api("com.google.guava:guava:32.0.0-jre")
}